"""add email_verification_ttl_hours to platform_settings

Revision ID: e22c3090448b
Revises: 5dd4c75c84c9
Create Date: 2026-08-11 10:16:11.515822
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e22c3090448b"
down_revision: str | None = "3db967736365"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "platform_settings",
        sa.Column("email_verification_ttl_hours", sa.Integer(), server_default=sa.text("24"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("platform_settings", "email_verification_ttl_hours")
    # ### end Alembic commands ###
