"""add terms documents and user consent columns

Revision ID: b11ddc8b3dce
Revises: 308cc687e191
Create Date: 2026-09-02 12:33:12.522087
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "b11ddc8b3dce"
down_revision: str | None = "308cc687e191"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terms_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.Uuid(), nullable=True),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms_documents")),
    )
    op.create_index(op.f("ix_terms_documents_published_at"), "terms_documents", ["published_at"], unique=False)
    op.create_index(
        "ix_terms_documents_version",
        "terms_documents",
        ["version"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column("users", sa.Column("accepted_terms_id", sa.Uuid(), nullable=True))
    op.add_column("users", sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("consent_emails", sa.Boolean(), server_default="false", nullable=False))
    op.create_index(op.f("ix_users_accepted_terms_id"), "users", ["accepted_terms_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_users_accepted_terms_id_terms_documents"),
        "users",
        "terms_documents",
        ["accepted_terms_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_accepted_terms_id_terms_documents"), "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_accepted_terms_id"), table_name="users")
    op.drop_column("users", "consent_emails")
    op.drop_column("users", "terms_accepted_at")
    op.drop_column("users", "accepted_terms_id")
    op.drop_index(
        "ix_terms_documents_version", table_name="terms_documents", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_terms_documents_published_at"), table_name="terms_documents")
    op.drop_table("terms_documents")
    # ### end Alembic commands ###
