"""add annotation labels

Schema only — the curated rows are code-owned reference data, upserted by
`sync_annotation_labels` as a deploy step after `migrate` (the curated-licences pattern), so
the catalog can change without a migration per edit.

Written by hand rather than autogenerated: the per-author index is an expression index on
`lower(name)`, which autogenerate does not reliably round-trip.

Revision ID: dbb137aac716
Revises: 4fd9bfdbdc1f
Create Date: 2026-08-28 13:30:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "dbb137aac716"
down_revision: str | None = "4fd9bfdbdc1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "annotation_labels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_id", sa.Uuid(), nullable=True),
        # NULL = curated (the catalog's `key` is its identity); set = a label an annotator
        # named, which carries no key. Nothing writes the non-null case until the annotation
        # entity lands — the column is here so the table is created in its final shape rather
        # than altered by the very next migration.
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        # No delete rule: users soft-delete, so a hard delete is refused. `SET NULL` is not
        # available either — it would leave neither an author nor a key, violating the CHECK.
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_annotation_labels_created_by_id_users")),
        # Curated xor authored, enforced rather than merely documented: the partial indexes
        # below do not span the two kinds, so a hybrid row would satisfy both and belong to
        # neither vocabulary.
        sa.CheckConstraint(
            "(created_by_id IS NULL) = (key IS NOT NULL)",
            name=op.f("ck_annotation_labels_kind_is_curated_xor_authored"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotation_labels")),
    )
    op.create_index(op.f("ix_annotation_labels_created_by_id"), "annotation_labels", ["created_by_id"])
    # Curated identity: one live row per key. Cross-kind collision is the CHECK's doing, not
    # this predicate's — an annotator's row cannot carry a key. Partial on live rows, so a
    # retired key can be re-added.
    op.create_index(
        "ix_annotation_labels_key",
        "annotation_labels",
        ["key"],
        unique=True,
        postgresql_where=sa.text("created_by_id IS NULL AND deleted_at IS NULL"),
    )
    # Per-author identity: one entry per (author, folded name), so an annotator who names
    # "Jailbreak" then "jailbreak" gets one label. Folded in Postgres, never Python — the two
    # disagree on dotted capitals.
    op.create_index(
        "ix_annotation_labels_author_name",
        "annotation_labels",
        ["created_by_id", sa.text("lower(name)")],
        unique=True,
        postgresql_where=sa.text("created_by_id IS NOT NULL AND deleted_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "ix_annotation_labels_author_name",
        table_name="annotation_labels",
        postgresql_where=sa.text("created_by_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_annotation_labels_created_by_id"), table_name="annotation_labels")
    op.drop_index(
        "ix_annotation_labels_key",
        table_name="annotation_labels",
        postgresql_where=sa.text("created_by_id IS NULL AND deleted_at IS NULL"),
    )
    op.drop_table("annotation_labels")
