"""add ai model description

Revision ID: c549e66b6e91
Revises: e22c3090448b
Create Date: 2026-08-17 10:54:09.679313
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c549e66b6e91"
down_revision: str | None = "e22c3090448b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_models", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_models", "description")
    # ### end Alembic commands ###
