"""add deleted_by_id for restore scoping

Revision ID: 3db967736365
Revises: 5dd4c75c84c9
Create Date: 2026-08-13 11:21:54.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3db967736365"
down_revision: str | None = "5dd4c75c84c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_models", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("annotations", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("audit_logs", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("conversation_groups", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("conversations", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("data_licenses", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("email_verifications", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("evaluation_ai_models", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("evaluation_group_ai_models", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("evaluation_groups", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("evaluation_tag_keys", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("evaluations", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("export_jobs", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("invitations", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("media_assets", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("message_flags", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("messages", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("notifications", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("object_role_assignments", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("organizations", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("outbound_emails", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("password_reset_tokens", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("platform_settings", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("provider_identities", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("reviews", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("roles", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("saved_views", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("scenarios", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("task_completions", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("tasks", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("turns", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    op.add_column("users", sa.Column("deleted_by_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_by_id")
    op.drop_column("turns", "deleted_by_id")
    op.drop_column("tasks", "deleted_by_id")
    op.drop_column("task_completions", "deleted_by_id")
    op.drop_column("scenarios", "deleted_by_id")
    op.drop_column("saved_views", "deleted_by_id")
    op.drop_column("roles", "deleted_by_id")
    op.drop_column("reviews", "deleted_by_id")
    op.drop_column("provider_identities", "deleted_by_id")
    op.drop_column("platform_settings", "deleted_by_id")
    op.drop_column("password_reset_tokens", "deleted_by_id")
    op.drop_column("outbound_emails", "deleted_by_id")
    op.drop_column("organizations", "deleted_by_id")
    op.drop_column("object_role_assignments", "deleted_by_id")
    op.drop_column("notifications", "deleted_by_id")
    op.drop_column("messages", "deleted_by_id")
    op.drop_column("message_flags", "deleted_by_id")
    op.drop_column("media_assets", "deleted_by_id")
    op.drop_column("invitations", "deleted_by_id")
    op.drop_column("export_jobs", "deleted_by_id")
    op.drop_column("evaluations", "deleted_by_id")
    op.drop_column("evaluation_tag_keys", "deleted_by_id")
    op.drop_column("evaluation_groups", "deleted_by_id")
    op.drop_column("evaluation_group_ai_models", "deleted_by_id")
    op.drop_column("evaluation_ai_models", "deleted_by_id")
    op.drop_column("email_verifications", "deleted_by_id")
    op.drop_column("data_licenses", "deleted_by_id")
    op.drop_column("conversations", "deleted_by_id")
    op.drop_column("conversation_groups", "deleted_by_id")
    op.drop_column("audit_logs", "deleted_by_id")
    op.drop_column("annotations", "deleted_by_id")
    op.drop_column("ai_models", "deleted_by_id")
    # ### end Alembic commands ###
