"""add object_role_assignments table

Revision ID: 3d7518b07fa1
Revises: 8e33bf5a3675
Create Date: 2026-06-10 10:39:56.250557
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3d7518b07fa1"
down_revision: str | None = "8e33bf5a3675"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_role_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("object_type", sa.Enum("evaluation_group", name="objecttype"), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_object_role_assignments_role_id_roles")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_object_role_assignments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_role_assignments")),
    )
    op.create_index(
        "ix_object_role_assignments_object_user_role",
        "object_role_assignments",
        ["object_type", "object_id", "user_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # Hand-added: serves the per-(user, object_type) visibility subquery (runs on
    # every group listing) and the user_id FK delete cascade — neither can use the
    # composite unique index above, which leads with object_type/object_id.
    op.create_index(
        "ix_object_role_assignments_user_object_type",
        "object_role_assignments",
        ["user_id", "object_type"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_object_role_assignments_user_object_type",
        table_name="object_role_assignments",
    )
    op.drop_index(
        "ix_object_role_assignments_object_user_role",
        table_name="object_role_assignments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("object_role_assignments")
    # The `objecttype` enum is created implicitly with the column above; drop it
    # explicitly so a downgrade fully reverses the upgrade (matches the enum
    # convention in the evaluation_groups migration).
    sa.Enum(name="objecttype").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
