"""add format column to export_jobs

Revision ID: 277f1d934f10
Revises: c37852e09173
Create Date: 2026-07-14 13:19:55.420061
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "277f1d934f10"
down_revision: str | None = "c37852e09173"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "export_jobs",
        sa.Column("format", sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'csv'"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("export_jobs", "format")
    # ### end Alembic commands ###
