"""add conversation groups and grouping

Revision ID: 4e501d145306
Revises: 5f017f1b5231
Create Date: 2026-06-19 11:54:45.933873
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "4e501d145306"
down_revision: str | None = "5f017f1b5231"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_conversation_groups_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_conversation_groups_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_conversation_groups_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_groups")),
    )
    op.create_index(
        op.f("ix_conversation_groups_evaluation_id"), "conversation_groups", ["evaluation_id"], unique=False
    )
    op.create_index(op.f("ix_conversation_groups_scenario_id"), "conversation_groups", ["scenario_id"], unique=False)
    op.create_index(op.f("ix_conversation_groups_user_id"), "conversation_groups", ["user_id"], unique=False)
    op.add_column("conversations", sa.Column("conversation_group_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_conversations_conversation_group_id"), "conversations", ["conversation_group_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_conversations_conversation_group_id_conversation_groups"),
        "conversations",
        "conversation_groups",
        ["conversation_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_conversations_conversation_group_id_conversation_groups"), "conversations", type_="foreignkey"
    )
    op.drop_index(op.f("ix_conversations_conversation_group_id"), table_name="conversations")
    op.drop_column("conversations", "conversation_group_id")
    op.drop_index(op.f("ix_conversation_groups_user_id"), table_name="conversation_groups")
    op.drop_index(op.f("ix_conversation_groups_scenario_id"), table_name="conversation_groups")
    op.drop_index(op.f("ix_conversation_groups_evaluation_id"), table_name="conversation_groups")
    op.drop_table("conversation_groups")
    # ### end Alembic commands ###
