"""add task_completions

Revision ID: d0e42f0530c4
Revises: 6280e9a08c17
Create Date: 2026-07-10 11:49:27.424106
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d0e42f0530c4"
down_revision: str | None = "6280e9a08c17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_completions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_group_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_group_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_group_id"],
            ["conversation_groups.id"],
            name=op.f("fk_task_completions_conversation_group_id_conversation_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_task_completions_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_task_completions_created_by_id_users")),
        sa.ForeignKeyConstraint(
            ["evaluation_group_id"],
            ["evaluation_groups.id"],
            name=op.f("fk_task_completions_evaluation_group_id_evaluation_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_task_completions_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_task_completions_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_completions_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_completions")),
    )
    op.create_index(
        "ix_task_completions_conversation_group_id", "task_completions", ["conversation_group_id"], unique=False
    )
    op.create_index(
        "ix_task_completions_conversation_id_task_id",
        "task_completions",
        ["conversation_id", "task_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_task_completions_created_by_id"), "task_completions", ["created_by_id"], unique=False)
    op.create_index(
        "ix_task_completions_evaluation_group_id", "task_completions", ["evaluation_group_id"], unique=False
    )
    op.create_index("ix_task_completions_evaluation_id", "task_completions", ["evaluation_id"], unique=False)
    op.create_index(op.f("ix_task_completions_scenario_id"), "task_completions", ["scenario_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_completions_scenario_id"), table_name="task_completions")
    op.drop_index("ix_task_completions_evaluation_id", table_name="task_completions")
    op.drop_index("ix_task_completions_evaluation_group_id", table_name="task_completions")
    op.drop_index(op.f("ix_task_completions_created_by_id"), table_name="task_completions")
    op.drop_index(
        "ix_task_completions_conversation_id_task_id",
        table_name="task_completions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_task_completions_conversation_group_id", table_name="task_completions")
    op.drop_table("task_completions")
    # ### end Alembic commands ###
