"""add turns and messages tables

Revision ID: b3b5c2bcbd8b
Revises: be9a7fe96307
Create Date: 2026-06-16 12:30:57.741574
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b3b5c2bcbd8b"
down_revision: str | None = "be9a7fe96307"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_turns_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
    )
    op.create_index("ix_turns_conversation_id_turn_index", "turns", ["conversation_id", "turn_index"], unique=True)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Enum("user", "assistant", "system", name="messagerole"), nullable=False),
        sa.Column(
            "status", sa.Enum("streaming", "complete", "interrupted", "error", name="messagestatus"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("slot", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
        sa.Column("client_message_id", sa.Uuid(), nullable=True),
        sa.Column("replaces_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "extra", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["replaces_message_id"],
            ["messages.id"],
            name=op.f("fk_messages_replaces_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], name=op.f("fk_messages_turn_id_turns"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_client_message_id",
        "messages",
        ["client_message_id"],
        unique=True,
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.create_index(
        "ix_messages_replaces_message_id",
        "messages",
        ["replaces_message_id"],
        unique=True,
        postgresql_where=sa.text("replaces_message_id IS NOT NULL"),
    )
    op.create_index(
        "ix_messages_streaming",
        "messages",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'streaming'"),
    )
    op.create_index(op.f("ix_messages_turn_id"), "messages", ["turn_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_turn_id"), table_name="messages")
    op.drop_index("ix_messages_streaming", table_name="messages", postgresql_where=sa.text("status = 'streaming'"))
    op.drop_index(
        "ix_messages_replaces_message_id",
        table_name="messages",
        postgresql_where=sa.text("replaces_message_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_messages_client_message_id",
        table_name="messages",
        postgresql_where=sa.text("client_message_id IS NOT NULL"),
    )
    op.drop_table("messages")
    op.drop_index("ix_turns_conversation_id_turn_index", table_name="turns")
    op.drop_table("turns")
    # Enum types are auto-created by sa.Enum in create_table but not auto-dropped;
    # remove them so a re-upgrade doesn't hit "type already exists".
    sa.Enum(name="messagestatus").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="messagerole").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
