"""add supports_image_input to ai_models

Revision ID: e4ccc7259477
Revises: d337239af41c
Create Date: 2026-07-10 16:50:30.814926
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e4ccc7259477"
down_revision: str | None = "d337239af41c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_models", sa.Column("supports_image_input", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_models", "supports_image_input")
    # ### end Alembic commands ###
