"""add conversations table

Revision ID: be9a7fe96307
Revises: fb35a765a2b2
Create Date: 2026-06-15 16:29:47.235608
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "be9a7fe96307"
down_revision: str | None = "fb35a765a2b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_ai_model_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_ai_model_id"],
            ["evaluation_ai_models.id"],
            name=op.f("fk_conversations_evaluation_ai_model_id_evaluation_ai_models"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_conversations_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenarios.id"], name=op.f("fk_conversations_scenario_id_scenarios"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_conversations_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_evaluation_ai_model_id"), "conversations", ["evaluation_ai_model_id"], unique=False
    )
    op.create_index(op.f("ix_conversations_evaluation_id"), "conversations", ["evaluation_id"], unique=False)
    op.create_index(op.f("ix_conversations_scenario_id"), "conversations", ["scenario_id"], unique=False)
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_scenario_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_evaluation_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_evaluation_ai_model_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
