"""add media asset is_private

Revision ID: cda1d243d37f
Revises: 7236c8d82b30
Create Date: 2026-07-14 20:51:29.557738
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "cda1d243d37f"
down_revision: str | None = "7236c8d82b30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_assets", sa.Column("is_private", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_assets", "is_private")
    # ### end Alembic commands ###
