"""add provider_identities table, plus users.password_cleared_at

Revision ID: 4a914e5b563b
Revises: 4849687935f4
Create Date: 2026-08-10 12:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "4a914e5b563b"
down_revision: str | None = "4849687935f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_provider_identities_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_identities")),
    )
    op.create_index(
        "ix_provider_identities_provider_subject",
        "provider_identities",
        ["provider", "subject"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_provider_identities_user_id"), "provider_identities", ["user_id"], unique=False)
    op.add_column("users", sa.Column("password_cleared_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A downgrade+re-upgrade cycle loses this column's data, not just its schema: every
    # account currently recovering from an OIDC-triggered password clear (see
    # `oidc.py::_activate`) silently reclassifies as a pure-IdP account with no self-service
    # password-reset path — same shape as it never having been cleared. Expected of an
    # added-then-used column on a real downgrade, not a bug here, but worth knowing before
    # running one against a database with live rows.
    op.drop_column("users", "password_cleared_at")
    op.drop_index(op.f("ix_provider_identities_user_id"), table_name="provider_identities")
    op.drop_index(
        "ix_provider_identities_provider_subject",
        table_name="provider_identities",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("provider_identities")
    # ### end Alembic commands ###
