"""create outbound_emails table

Revision ID: ed4312c997fb
Revises: 79d9cded6c9f
Create Date: 2026-05-20 11:47:14.207961
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ed4312c997fb"
down_revision: str | None = "79d9cded6c9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_emails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("template_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("backend", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(length=998), nullable=True),
        sa.Column("status", sa.Enum("queued", "sent", "failed", name="outboundemailstatus"), nullable=False),
        sa.Column("error_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("celery_task_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("provider_message_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_emails")),
    )
    op.create_index(op.f("ix_outbound_emails_celery_task_id"), "outbound_emails", ["celery_task_id"], unique=False)
    op.create_index(
        op.f("ix_outbound_emails_provider_message_id"), "outbound_emails", ["provider_message_id"], unique=False
    )
    op.create_index(op.f("ix_outbound_emails_recipient"), "outbound_emails", ["recipient"], unique=False)
    op.create_index(op.f("ix_outbound_emails_status"), "outbound_emails", ["status"], unique=False)
    op.create_index(op.f("ix_outbound_emails_template_name"), "outbound_emails", ["template_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbound_emails_template_name"), table_name="outbound_emails")
    op.drop_index(op.f("ix_outbound_emails_status"), table_name="outbound_emails")
    op.drop_index(op.f("ix_outbound_emails_recipient"), table_name="outbound_emails")
    op.drop_index(op.f("ix_outbound_emails_provider_message_id"), table_name="outbound_emails")
    op.drop_index(op.f("ix_outbound_emails_celery_task_id"), table_name="outbound_emails")
    op.drop_table("outbound_emails")
    # Drop the enum type explicitly — autogenerate leaves it behind, where it would
    # outlive its only column and break a subsequent upgrade.
    sa.Enum(name="outboundemailstatus").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
