"""add role activation flags

Revision ID: 5195eaa359f1
Revises: b57a85aeaa5d
Create Date: 2026-08-03 13:25:12.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5195eaa359f1"
down_revision: str | None = "b57a85aeaa5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False))
    op.add_column("roles", sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column(
        "roles", sa.Column("is_participant_default", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "roles", sa.Column("is_object_assignable", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.create_index(
        "ix_roles_is_default",
        "roles",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_roles_is_participant_default",
        "roles",
        ["is_participant_default"],
        unique=True,
        postgresql_where=sa.text("is_participant_default AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
    # Create-only sync won't stamp already-provisioned roles; seed both default
    # flags onto the canonical default-participant role so existing DBs have a
    # new-user default and a self-join participant default.
    op.execute(
        "UPDATE roles SET is_default = true, is_participant_default = true "
        "WHERE name = 'red_teamer' AND deleted_at IS NULL"
    )
    # Object-assignability is code-owned for system roles (the object-role
    # registry); stamp the current policy so provisioned DBs keep their in-group
    # roles assignable before the next `sync_system_roles` run.
    op.execute(
        "UPDATE roles SET is_object_assignable = true "
        "WHERE name IN ('owner', 'red_teamer', 'annotator', 'viewer') AND deleted_at IS NULL"
    )
    # An inactive default would make its resolver raise and 500 every registration
    # or self-join; enforce the invariant at the DB after the backfill.
    op.create_check_constraint("default_role_active", "roles", "NOT (is_default AND NOT is_active)")
    op.create_check_constraint(
        "participant_default_role_active", "roles", "NOT (is_participant_default AND NOT is_active)"
    )
    # Self-join grants the participant default as an object role without passing
    # through assignment validation; both backfills above already satisfy this.
    op.create_check_constraint(
        "participant_default_role_assignable", "roles", "NOT (is_participant_default AND NOT is_object_assignable)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("participant_default_role_assignable", "roles", type_="check")
    op.drop_constraint("participant_default_role_active", "roles", type_="check")
    op.drop_constraint("default_role_active", "roles", type_="check")
    op.drop_index(
        "ix_roles_is_participant_default",
        table_name="roles",
        postgresql_where=sa.text("is_participant_default AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_roles_is_default", table_name="roles", postgresql_where=sa.text("is_default AND deleted_at IS NULL")
    )
    op.drop_column("roles", "is_object_assignable")
    op.drop_column("roles", "is_participant_default")
    op.drop_column("roles", "is_default")
    op.drop_column("roles", "is_active")
    # ### end Alembic commands ###
