"""add ai_models table

Revision ID: 87349019bfdd
Revises: b5cfc423b1f2
Create Date: 2026-05-28 16:22:58.687690
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "87349019bfdd"
down_revision: str | None = "b5cfc423b1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("model_alias", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "huggingface",
                "google",
                "openai",
                "anthropic",
                "azure",
                "generic",
                "aws_bedrock",
                "cohere",
                name="providervendor",
            ),
            nullable=False,
        ),
        sa.Column("modality", sa.Enum("text_to_text", "text_to_image", name="modelmodality"), nullable=False),
        sa.Column("provider_model_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("endpoint_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("inference_endpoint", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("icon_file", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "extras", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("api_key_encrypted", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_models")),
    )
    op.create_index(
        "ix_ai_models_model_alias",
        "ai_models",
        ["model_alias"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_ai_models_name", "ai_models", ["name"], unique=True, postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index(op.f("ix_ai_models_provider"), "ai_models", ["provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_models_provider"), table_name="ai_models")
    op.drop_index("ix_ai_models_name", table_name="ai_models", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_index("ix_ai_models_model_alias", table_name="ai_models", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("ai_models")
    # Autogenerate omits ENUM-type cleanup; the orphan PG types break re-upgrade.
    sa.Enum(name="modelmodality").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="providervendor").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
