"""add created_by_id to evaluations

Revision ID: 1dc3106004d6
Revises: 509642f23c24
Create Date: 2026-06-09 11:24:00.005101
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1dc3106004d6"
down_revision: str | None = "509642f23c24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluations", sa.Column("created_by_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_evaluations_created_by_id"), "evaluations", ["created_by_id"], unique=False)
    op.create_foreign_key(op.f("fk_evaluations_created_by_id_users"), "evaluations", "users", ["created_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_evaluations_created_by_id_users"), "evaluations", type_="foreignkey")
    op.drop_index(op.f("ix_evaluations_created_by_id"), table_name="evaluations")
    op.drop_column("evaluations", "created_by_id")
    # ### end Alembic commands ###
