"""export jobs

Revision ID: 6ce78e71b124
Revises: faf31876b80a
Create Date: 2026-07-02 09:51:10.176267
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "6ce78e71b124"
down_revision: str | None = "faf31876b80a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("template", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=True),
        sa.Column("evaluation_group_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "ready", "failed", name="exportjobstatus"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("file_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_group_id"],
            ["evaluation_groups.id"],
            name=op.f("fk_export_jobs_evaluation_group_id_evaluation_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_export_jobs_evaluation_id_evaluations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"], ["users.id"], name=op.f("fk_export_jobs_requested_by_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_jobs")),
    )
    op.create_index(op.f("ix_export_jobs_requested_by_id"), "export_jobs", ["requested_by_id"], unique=False)
    op.create_index(
        "ix_export_jobs_requester_idempotency_key",
        "export_jobs",
        ["requested_by_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_export_jobs_status"), "export_jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_export_jobs_status"), table_name="export_jobs")
    op.drop_index(
        "ix_export_jobs_requester_idempotency_key",
        table_name="export_jobs",
        postgresql_where=sa.text("idempotency_key IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_export_jobs_requested_by_id"), table_name="export_jobs")
    op.drop_table("export_jobs")
    # Enum types are auto-created by sa.Enum in create_table but not auto-dropped;
    # drop explicitly so a down-migration leaves no orphaned type behind.
    sa.Enum(name="exportjobstatus").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
