"""add image_key to messages

Revision ID: c37852e09173
Revises: e4ccc7259477
Create Date: 2026-07-10 16:57:14.704703
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "c37852e09173"
down_revision: str | None = "e4ccc7259477"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("image_key", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "image_key")
    # ### end Alembic commands ###
