"""multi image message attachments

Revision ID: 87bd993fdf39
Revises: cda1d243d37f
Create Date: 2026-07-14 21:01:39.233321
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "87bd993fdf39"
down_revision: str | None = "cda1d243d37f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_images",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("image_key", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_message_images_message_id_messages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("message_id", "position", name=op.f("pk_message_images")),
    )
    # Backfill the single-image column into link rows (position 0) before dropping it.
    op.execute(
        "INSERT INTO message_images (message_id, position, image_key) "
        "SELECT id, 0, image_key FROM messages WHERE image_key IS NOT NULL"
    )
    op.drop_column("messages", "image_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("image_key", sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    # Fold link rows back into the column; only the first attachment survives the downgrade.
    op.execute(
        "UPDATE messages SET image_key = mi.image_key "
        "FROM message_images mi WHERE mi.message_id = messages.id AND mi.position = 0"
    )
    op.drop_table("message_images")
    # ### end Alembic commands ###
