"""add labels to ai models

Revision ID: f1d5ed29d7ff
Revises: 1e621963dca6
Create Date: 2026-08-19 11:45:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f1d5ed29d7ff"
down_revision: str | None = "1e621963dca6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_models", sa.Column("labels", sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_models", "labels")
    # ### end Alembic commands ###
