"""add invite_only to platform_settings

Revision ID: 016524bf6c54
Revises: 4a914e5b563b
Create Date: 2026-08-11 08:44:46.554788
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "016524bf6c54"
down_revision: str | None = "4a914e5b563b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "platform_settings", sa.Column("invite_only", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("platform_settings", "invite_only")
    # ### end Alembic commands ###
