"""add title to conversations

Revision ID: 4c95955607dc
Revises: 6ce78e71b124
Create Date: 2026-07-02 14:11:55.462982
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "4c95955607dc"
down_revision: str | None = "6ce78e71b124"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "title")
    # ### end Alembic commands ###
