"""add filters column to export_jobs

Revision ID: 7236c8d82b30
Revises: 277f1d934f10
Create Date: 2026-07-13 15:16:02.792230
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7236c8d82b30"
down_revision: str | None = "277f1d934f10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("export_jobs", sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("export_jobs", "filters")
    # ### end Alembic commands ###
