"""add annotations and annotated messages

Revision ID: b57a85aeaa5d
Revises: c4d9f1a70b83
Create Date: 2026-08-03 10:45:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b57a85aeaa5d"
down_revision: str | None = "c4d9f1a70b83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_group_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_annotations_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_annotations_created_by_id_users")),
        sa.ForeignKeyConstraint(
            ["evaluation_group_id"],
            ["evaluation_groups.id"],
            name=op.f("fk_annotations_evaluation_group_id_evaluation_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_annotations_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotations")),
    )
    op.create_index("ix_annotations_conversation_id", "annotations", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_annotations_created_by_id"), "annotations", ["created_by_id"], unique=False)
    op.create_index("ix_annotations_evaluation_group_id", "annotations", ["evaluation_group_id"], unique=False)
    op.create_index("ix_annotations_evaluation_id", "annotations", ["evaluation_id"], unique=False)
    op.create_table(
        "annotated_messages",
        sa.Column("annotation_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_annotated_messages_annotation_id_annotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_annotated_messages_message_id_messages")
        ),
        sa.PrimaryKeyConstraint("annotation_id", "message_id", name=op.f("pk_annotated_messages")),
    )
    op.create_index("ix_annotated_messages_message_id", "annotated_messages", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_annotated_messages_message_id", table_name="annotated_messages")
    op.drop_table("annotated_messages")
    op.drop_index("ix_annotations_evaluation_id", table_name="annotations")
    op.drop_index("ix_annotations_evaluation_group_id", table_name="annotations")
    op.drop_index(op.f("ix_annotations_created_by_id"), table_name="annotations")
    op.drop_index("ix_annotations_conversation_id", table_name="annotations")
    op.drop_table("annotations")
    # ### end Alembic commands ###
