"""add ai_model health check fields

Revision ID: a2743b97e51d
Revises: 87bd993fdf39
Create Date: 2026-07-20 13:18:16.994052
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "a2743b97e51d"
down_revision: str | None = "87bd993fdf39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column does NOT auto-create the PG ENUM type in this setup (autogenerate omits it) — create it first.
    healthcheckstatus = sa.Enum("checking", "alive", "dead", name="healthcheckstatus")
    healthcheckstatus.create(op.get_bind(), checkfirst=True)
    op.add_column("ai_models", sa.Column("health_check_status", healthcheckstatus, nullable=True))
    op.add_column("ai_models", sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "ai_models", sa.Column("last_health_reason", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True)
    )
    op.add_column("ai_models", sa.Column("last_healthy_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_models", "last_healthy_at")
    op.drop_column("ai_models", "last_health_reason")
    op.drop_column("ai_models", "last_health_check_at")
    op.drop_column("ai_models", "health_check_status")
    # ### end Alembic commands ###
    # Autogenerate omits ENUM-type cleanup; the orphan PG type breaks re-upgrade.
    sa.Enum(name="healthcheckstatus").drop(op.get_bind(), checkfirst=False)
