"""add reviews table and scenario required_reviews

Revision ID: 5f017f1b5231
Revises: def9056c00d6
Create Date: 2026-06-18 11:08:23.930883
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5f017f1b5231"
down_revision: str | None = "def9056c00d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_flag_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="reviewstatus"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("successful_exploit", sa.Boolean(), nullable=True),
        sa.Column("unique_exploit", sa.Boolean(), nullable=True),
        sa.Column("valid_submission", sa.Boolean(), nullable=True),
        sa.Column("number_prompts", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_by_id"], ["users.id"], name=op.f("fk_reviews_assigned_by_id_users")),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.id"], name=op.f("fk_reviews_evaluation_id_evaluations"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["message_flag_id"],
            ["message_flags.id"],
            name=op.f("fk_reviews_message_flag_id_message_flags"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], name=op.f("fk_reviews_reviewer_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index("ix_reviews_evaluation_id", "reviews", ["evaluation_id"], unique=False)
    op.create_index(
        "ix_reviews_message_flag_id_reviewer_id",
        "reviews",
        ["message_flag_id", "reviewer_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_reviews_reviewer_id"), "reviews", ["reviewer_id"], unique=False)
    op.create_index(op.f("ix_reviews_status"), "reviews", ["status"], unique=False)
    op.add_column("scenarios", sa.Column("required_reviews", sa.Integer(), server_default=sa.text("1"), nullable=False))
    # Autogenerate misses CHECK constraints — add the positivity guard by hand.
    op.create_check_constraint(op.f("ck_scenarios_required_reviews_positive"), "scenarios", "required_reviews >= 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropping the column drops its CHECK constraint with it.
    op.drop_column("scenarios", "required_reviews")
    op.drop_index(op.f("ix_reviews_status"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_reviewer_id"), table_name="reviews")
    op.drop_index(
        "ix_reviews_message_flag_id_reviewer_id", table_name="reviews", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index("ix_reviews_evaluation_id", table_name="reviews")
    op.drop_table("reviews")
    # Enum types are auto-created by sa.Enum in create_table but not auto-dropped;
    # remove it so a re-upgrade doesn't hit "type already exists".
    sa.Enum(name="reviewstatus").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
