"""add password policy and reset throttling knobs

Revision ID: 1e621963dca6
Revises: c549e66b6e91
Create Date: 2026-08-19 10:21:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1e621963dca6"
down_revision: str | None = "c549e66b6e91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "platform_settings",
        sa.Column("password_min_length", sa.Integer(), server_default=sa.text("8"), nullable=False),
    )
    op.add_column(
        "platform_settings",
        sa.Column("password_require_uppercase", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "platform_settings",
        sa.Column("password_require_digit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "platform_settings",
        sa.Column("password_require_symbol", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "platform_settings",
        sa.Column("password_reset_cooldown_seconds", sa.Integer(), server_default=sa.text("60"), nullable=False),
    )
    op.add_column(
        "platform_settings",
        sa.Column("password_reset_max_per_day", sa.Integer(), server_default=sa.text("5"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("platform_settings", "password_reset_max_per_day")
    op.drop_column("platform_settings", "password_reset_cooldown_seconds")
    op.drop_column("platform_settings", "password_require_symbol")
    op.drop_column("platform_settings", "password_require_digit")
    op.drop_column("platform_settings", "password_require_uppercase")
    op.drop_column("platform_settings", "password_min_length")
    # ### end Alembic commands ###
