"""add message flags and flagged messages tables

Revision ID: def9056c00d6
Revises: b3b5c2bcbd8b
Create Date: 2026-06-16 15:29:27.574869
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "def9056c00d6"
down_revision: str | None = "b3b5c2bcbd8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("red_flagged", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="flagstatus"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_id", sa.Uuid(), nullable=False),
        sa.Column("evaluation_group_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_message_flags_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("fk_message_flags_created_by_id_users")),
        sa.ForeignKeyConstraint(
            ["evaluation_group_id"],
            ["evaluation_groups.id"],
            name=op.f("fk_message_flags_evaluation_group_id_evaluation_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
            name=op.f("fk_message_flags_evaluation_id_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenarios.id"], name=op.f("fk_message_flags_scenario_id_scenarios"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_message_flags_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_flags")),
    )
    op.create_index("ix_message_flags_conversation_id", "message_flags", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_message_flags_created_by_id"), "message_flags", ["created_by_id"], unique=False)
    op.create_index("ix_message_flags_evaluation_group_id", "message_flags", ["evaluation_group_id"], unique=False)
    op.create_index("ix_message_flags_evaluation_id", "message_flags", ["evaluation_id"], unique=False)
    op.create_index(op.f("ix_message_flags_scenario_id"), "message_flags", ["scenario_id"], unique=False)
    op.create_index(op.f("ix_message_flags_status"), "message_flags", ["status"], unique=False)
    op.create_index(op.f("ix_message_flags_task_id"), "message_flags", ["task_id"], unique=False)
    op.create_table(
        "flagged_messages",
        sa.Column("message_flag_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_flag_id"],
            ["message_flags.id"],
            name=op.f("fk_flagged_messages_message_flag_id_message_flags"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name=op.f("fk_flagged_messages_message_id_messages")),
        sa.PrimaryKeyConstraint("message_flag_id", "message_id", name=op.f("pk_flagged_messages")),
    )
    op.create_index("ix_flagged_messages_message_id", "flagged_messages", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_flagged_messages_message_id", table_name="flagged_messages")
    op.drop_table("flagged_messages")
    op.drop_index(op.f("ix_message_flags_task_id"), table_name="message_flags")
    op.drop_index(op.f("ix_message_flags_status"), table_name="message_flags")
    op.drop_index(op.f("ix_message_flags_scenario_id"), table_name="message_flags")
    op.drop_index("ix_message_flags_evaluation_id", table_name="message_flags")
    op.drop_index("ix_message_flags_evaluation_group_id", table_name="message_flags")
    op.drop_index(op.f("ix_message_flags_created_by_id"), table_name="message_flags")
    op.drop_index("ix_message_flags_conversation_id", table_name="message_flags")
    op.drop_table("message_flags")
    # Enum types are auto-created by sa.Enum in create_table but not auto-dropped;
    # remove them so a re-upgrade doesn't hit "type already exists".
    sa.Enum(name="flagstatus").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
