"""add organizations and user + evaluation_group organization_id

Revision ID: de0ad3da2fe0
Revises: 73db67c194cb
Create Date: 2026-06-24 14:21:40.882279
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "de0ad3da2fe0"
down_revision: str | None = "73db67c194cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TYPE evaluationgroupaccesslevel ADD VALUE IF NOT EXISTS 'organization'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        "ix_organizations_name", "organizations", ["name"], unique=True, postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.add_column("users", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_users_organization_id_organizations"),
        "users",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("evaluation_groups", sa.Column("organization_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_evaluation_groups_organization_id"), "evaluation_groups", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_evaluation_groups_organization_id_organizations"),
        "evaluation_groups",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_evaluation_groups_organization_id_organizations"), "evaluation_groups", type_="foreignkey"
    )
    op.drop_index(op.f("ix_evaluation_groups_organization_id"), table_name="evaluation_groups")
    op.drop_column("evaluation_groups", "organization_id")
    op.drop_constraint(op.f("fk_users_organization_id_organizations"), "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_column("users", "organization_id")
    op.drop_index("ix_organizations_name", table_name="organizations", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("organizations")
    # ### end Alembic commands ###
